# Generated by Django 6.0.6 on 2026-06-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(choices=[('inundacion', 'Inundación'), ('derrumbe', 'Derrumbe / Deslave'), ('arbol', 'Árbol Caído')], max_length=20)),
                ('descripcion', models.TextField()),
                ('evidencia', models.ImageField(blank=True, null=True, upload_to='evidencias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
